### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by incurito** [electron/grunt-electron-installer#101]
I am trying to use the grunt plugin to create a windows installer for my electron app and it fails when I run the setup.exe. I am using 1.2.1. I have included the gist from SquirrelSetup. Any pointers would be helpful.

```
2016-02-11 00:52:26> Program: Starting Squirrel Updater: --install .
2016-02-11 00:52:27> Program: Starting install, writing to C:\Users\IEUser\AppData\Local\SquirrelTemp
2016-02-11 00:52:27> Program: About to install to: C:\Users\IEUser\AppData\Local\desktop
2016-02-11 00:52:27> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\IEUser\AppData\Local\desktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-02-11 00:52:27> CheckForUpdateImpl: Reading RELEASES file from C:\Users\IEUser\AppData\Local\SquirrelTemp
2016-02-11 00:52:27> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-02-11 00:52:28> ApplyReleasesImpl: Writing files to app directory: C:\Users\IEUser\AppData\Local\desktop\app-0.0.0
2016-02-11 00:52:33> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\content_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\content_resources_200_percent.pak
2016-02-11 00:52:33> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\content_shell.pak to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\content_shell.pak
2016-02-11 00:52:33> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\d3dcompiler_47.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\d3dcompiler_47.dll
2016-02-11 00:52:33> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\MyApp.exe to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\MyApp.exe
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\icudtl.dat to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\icudtl.dat
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\libEGL.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\libEGL.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\libGLESv2.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\libGLESv2.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\LICENSE to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\LICENSE
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\msvcp120.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\msvcp120.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\msvcr120.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\msvcr120.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\natives_blob.bin to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\natives_blob.bin
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\node.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\node.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\pdf.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\pdf.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\snapshot_blob.bin to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\snapshot_blob.bin
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\squirrel.exe to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\squirrel.exe
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\ui_resources_200_percent.pak to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\ui_resources_200_percent.pak
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\vccorlib120.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\vccorlib120.dll
2016-02-11 00:52:35> ApplyReleasesImpl: Moving file C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\lib\net45\xinput1_3.dll to C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\xinput1_3.dll
2016-02-11 00:52:37> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\IEUser\AppData\Local\desktop\app-0.0.0\MyApp.exe]
2016-02-11 00:52:42> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-02-11 00:52:42> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2016-02-11 00:52:42> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2016-02-11 00:52:42> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2016-02-11 00:52:42> ApplyReleasesImpl: Fixing up tray icons
2016-02-11 00:52:42> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.0
2016-02-11 00:52:42> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.0
2016-02-11 00:52:42> IEnableLogger: Failed to create uninstaller registry entry: System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2016-02-11 00:52:42> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Xml.XmlException: 'Default' tag requires a nonempty 'Extension' attribute. Line 10, position 4.
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ValidateXmlAttribute(String attributeName, String attributeValue, String tagName, XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessDefaultTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at NuGet.ZipPackage..ctor(String filePath)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

```

**Comment by havenchyk** [comment]
@incurito could you please try again with https://github.com/electronjs/windows-installer ? It's the same package, but without grunt and with a couple of solved issues.

**Comment by havenchyk** [comment]
There is no response. Feel free to reopen if you still have this problem.
